/* Adapt legacy Topic content to the authoritative shared study UI; editors remain intact. */
(function(){
'use strict';
let frame=null;
const safeJSON=value=>JSON.stringify(value).replace(/</g,'\\u003c');
const rawQuiz=startQuiz,rawCards=studyFlashSet;
async function openTopicStudy(topicId,kind='dashboard',setId=null,filter='all'){
 try{
  const topic=await Storage.get('topics',topicId);if(!topic)throw Error('Topic is unavailable.');await frame?.contentWindow?.studyFlush?.();
  const [allQ,allC,setsQ,setsC,progress,source,conceptRow]=await Promise.all(['questions','flashcards','quizSets','flashcardSets','progress','materials'].map(store=>Storage.queryBy(store,'topicId',topicId)).concat(Storage.get('meta','topicConcepts:'+topicId)));
  const qs=allQ.filter(q=>q.topicId===topicId),cs=allC.filter(c=>c.topicId===topicId),ps=progress.filter(p=>p.topicId===topicId);
  const id='topic:'+topicId;
  const concepts=(conceptRow?.value?.concepts||[]).map(c=>({...c,topicId}));
  const model={questions:qs.map(q=>({key:'mcq:'+q.id,legacyId:q.id,kind:'mcq',prompt:q.text,options:q.options,correct:q.correct,explanations:q.optionExplanations,explanation:q.explanation,hint:q.hint,topicId,unitId:q.setId,conceptId:q.conceptId||'unmapped:mcq:'+q.id,conceptTitle:q.text,source:q.source||null,difficulty:q.difficulty,cognitiveLevel:q.cognitiveLevel,tags:q.tags,setId:q.setId})),cards:cs.map(c=>({key:'card:'+c.id,legacyId:c.id,kind:'card',front:c.front,back:c.back,topicId,unitId:c.setId,conceptId:c.conceptId||'unmapped:card:'+c.id,conceptTitle:c.front,source:c.source||null,setId:c.setId})),concepts,topics:[{id:topicId,title:topic.name,unitTitle:'Topic',facts:[],source:null}],sourceCount:source.filter(m=>m.topicId===topicId).length,unlinkedSourceCount:source.filter(m=>m.topicId===topicId).length,sourceWarnings:concepts.length?[]:['Source concepts have not been fully mapped. Item coverage measures the existing bank, not complete PDF or lecture coverage. Use Source Concept Map to add missing concepts.']};
  const invalid=model.questions.filter(q=>!UniversalStudyCore.validateQuestion(q));if(invalid.length)toast(invalid.length+' invalid questions kept in the editor and excluded from practice.');
  let mirrored=Promise.resolve();
  window.TopicStudyHost={async exit(tool){await frame?.contentWindow?.studyFlush?.();closeSheet();State.topicId=topicId;State.subjectId=topic.subjectId;State.topicTool=tool;go('topic',{topicId,subjectId:topic.subjectId,topicTool:tool})},
   mirror(item,r,answer){r=structuredClone(r);const key=(item.kind==='mcq'?'q:':'fc:')+item.legacyId;mirrored=mirrored.then(async()=>{const old=await Storage.get('progress',key)||{id:key,topicId,kind:item.kind==='mcq'?'question':'flashcard',questionId:item.kind==='mcq'?item.legacyId:undefined,cardId:item.kind==='card'?item.legacyId:undefined,attempts:[],createdAt:now()};const next={...old,studySchemaVersion:2,studyRecord:structuredClone(r),lastCorrect:r.lastResult==='correct',lastConfidence:r.lastConfidence,lastStudied:r.lastAt,missed:r.incorrect,improved:!!r.mastered};if(item.kind==='mcq'){const event=r.events.at(-1);if(event?.correct!==undefined){next.attempts=[...(Array.isArray(old.attempts)?old.attempts:[])];if(!next.attempts.some(e=>e.id===event.id))next.attempts.push({...event,selectedText:answer});}}await Storage.put('progress',next)});return mirrored;},flush:()=>mirrored};
  const payload={id,title:topic.name,model,legacy:{progress:ps},kind,setId,filter};
  const adapter=`(function(){const p=${safeJSON(payload)};let legacy=p.legacy;window.StudyModuleAdapter={id:p.id,title:p.title,legacyKey:'topic-progress:'+p.id,sourceDescription:'Your preserved Topic materials',externalViews:['reader','notes','tables','compare','original-guide','original-recall'],openExternal(view){parent.TopicStudyHost.exit(({ 'original-guide':'overview','original-recall':'flashcards',compare:'tables'})[view]||view).catch(e=>alert(e.message))},getLegacy:()=>legacy,setLegacy(v){legacy=v},mergeLegacy(v){legacy={...v,...legacy}},setMode(){},content:()=>p.model,legacyEvidence(item,old){const row=(old.progress||[]).find(r=>r.id===(item.kind==='mcq'?'q:':'fc:')+item.legacyId);if(!row)return null;if(row.studyRecord)return row.studyRecord;const attempts=Array.isArray(row.attempts)?row.attempts:[];return{attempts:attempts.length,correct:attempts.filter(a=>a.correct).length,incorrect:attempts.filter(a=>!a.correct).length,mastered:false,reviewAgain:(row.missed||0)>0&&!row.improved,lastAt:row.lastStudied||attempts.at(-1)?.at||null,lastResult:attempts.length?(attempts.at(-1).correct?'correct':'incorrect'):null,events:attempts.map((a,i)=>({...a,id:a.id||'legacy:'+item.key+':'+i})),provenance:'legacy'}},legacyMistakes(old){return(old.progress||[]).filter(r=>r.kind==='question').flatMap(r=>(r.attempts||[]).filter(a=>!a.correct).map(a=>({key:'mcq:'+r.questionId,at:a.at,learnerAnswer:a.selectedText||'Legacy option index '+a.selected,confidence:a.confidence,resolved:!!r.improved,category:'Knowledge gap'})))},legacyWeakTopics:()=>[],legacySession:()=>[],legacyPosition:()=>0,mirrorEvidence:(item,r,answer)=>parent.TopicStudyHost.mirror(item,structuredClone(r),answer),flush:()=>parent.TopicStudyHost.flush(),panel:()=>null,connectNavigation(){},readerInfo:()=>({index:0,total:0,label:'Topic sources'}),readerItems:()=>[],activateSource(){},jumpSource(source){parent.TopicStudyHost.exit('reader').then(()=>{if(source.materialId)parent.openMaterial(source.materialId).then(()=>{if(source.page&&parent.pdfGoPage)parent.pdfGoPage(source.page)})})}};const check=setInterval(()=>{if(!window.StudyApp?.ready)return;clearInterval(check);const app=window.StudyApp;if(!['mcq','flashcards','recall','exam'].includes(p.kind)){app.navigate(p.kind);return}const eligible=app.pool(p.kind,p.filter).filter(i=>!p.setId||i.setId===p.setId);if(!eligible.length){app.navigate('dashboard');return}const saved=app.data.sessions[p.kind];if(saved&&!saved.completedAt&&(!p.setId||saved.options?.setId===p.setId)){app.navigate(p.kind);return}app.data.sessions[p.kind]=app.createSession(p.kind,app.orderAdaptive(eligible).map(i=>i.key),'Topic '+p.kind,p.kind!=='exam',{setId:p.setId});app.navigate(p.kind);app.flush()},25)})();`;
  const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+SHARED_STUDY_CSS+'</style></head><body><div id="legacyModule"></div><script>'+UNIVERSAL_STUDY_CORE+'<'+ '/script><script>'+adapter+'<'+ '/script><script>'+SHARED_STUDY_ENGINE+'<'+ '/script></body></html>';
  openSheet('Study', '<iframe id="topicStudyFrame" title="Topic study module" style="width:100%;height:78dvh;border:0"></iframe>');frame=document.getElementById('topicStudyFrame');frame.srcdoc=html;
 }catch(error){StudyDataSafety.report(error);toast(error.message)}
}
window.openTopicStudy=openTopicStudy;
startQuiz=async id=>{const set=await Storage.get('quizSets',id);if(!set)return toast('Quiz set unavailable');return openTopicStudy(set.topicId,'mcq',id)};
studyFlashSet=async(id,shuffle=false)=>{const set=await Storage.get('flashcardSets',id);if(!set)return toast('Card set unavailable');return openTopicStudy(set.topicId,'flashcards',id)};
retryMistakes=()=>openTopicStudy(State.topicId,'mcq',null,'weak');
// Explicit compatibility escape hatch for recovery; neither old interface is deleted.
window.LegacyTopicStudy={quiz:rawQuiz,flashcards:rawCards};
const plainClose=closeSheet;closeSheet=async function(){const current=document.getElementById('topicStudyFrame');if(current){try{if(!current.contentWindow.studyFlush)return toast('Study module is still loading.');await current.contentWindow.studyFlush()}catch(e){toast('Save failed. Keep the study module open. '+e.message);return}}plainClose();frame=null};
const oldOverview=topicOverview;
topicOverview=async host=>{await oldOverview(host);host.insertAdjacentHTML('afterbegin',`<div class="card"><div class="section-head"><div class="h3">Study workspace</div><button class="btn primary" data-topic-study="dashboard">Study Now</button></div><div class="chips"><button class="btn" data-topic-study="mcq">MCQ</button><button class="btn" data-topic-study="flashcards">Flashcards</button><button class="btn" data-topic-study="recall">Active Recall</button><button class="btn" data-topic-study="coverage">Coverage</button><button class="btn" data-topic-concepts>Source Concept Map</button></div></div>`)};
document.addEventListener('click',event=>{const b=event.target.closest('[data-topic-study]');if(b)openTopicStudy(State.topicId,b.dataset.topicStudy);if(event.target.closest('[data-topic-concepts]'))conceptEditor();if(event.target.closest('[data-save-concepts]'))saveConcepts().catch(e=>toast(e.message));if(event.target.closest('[data-link-concept]'))linkConcept().catch(e=>toast(e.message))});
async function conceptEditor(){const id=State.topicId,[row,qs,cs,mats]=await Promise.all([Storage.get('meta','topicConcepts:'+id),Storage.queryBy('questions','topicId',id),Storage.queryBy('flashcards','topicId',id),Storage.queryBy('materials','topicId',id)]);const concepts=row?.value?.concepts||[];openSheet('Source Concept Map',`<p class="muted">Add one important source concept per line. Untested concepts remain visible. Existing IDs and links are retained.</p><textarea class="textarea" id="topicConceptLines">${esc(concepts.map(c=>c.title).join('\n'))}</textarea><button class="btn primary" data-save-concepts>Save concepts</button>${concepts.length?`<div class="field"><label>Study item</label><select class="select" id="conceptItem">${qs.map(q=>`<option value="${esc('questions:'+q.id)}">MCQ: ${esc(q.text.slice(0,100))}</option>`).join('')}${cs.map(c=>`<option value="${esc('flashcards:'+c.id)}">Card: ${esc(c.front.slice(0,100))}</option>`).join('')}</select></div><div class="field"><label>Concept</label><select class="select" id="conceptTarget">${concepts.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select></div><div class="field"><label>Source (optional)</label><select class="select" id="conceptMaterial"><option value="">No exact source recorded</option>${mats.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></div><div class="field"><label>Actual source page (optional)</label><input class="input" type="number" min="1" id="conceptPage"></div><button class="btn" data-link-concept>Link item to concept</button>`:''}`)}
async function linkConcept(){const raw=document.getElementById('conceptItem').value,split=raw.indexOf(':'),store=raw.slice(0,split),id=raw.slice(split+1),conceptId=document.getElementById('conceptTarget').value;if(!['questions','flashcards'].includes(store))throw Error('Choose a study item.');const item=await Storage.get(store,id);if(!item||item.topicId!==State.topicId)throw Error('Item is unavailable in this topic');item.conceptId=conceptId;const materialId=document.getElementById('conceptMaterial').value,pageText=document.getElementById('conceptPage').value;if(pageText&&!materialId)throw Error('Choose the actual source before recording a page');if(materialId){const material=await Storage.get('materials',materialId);if(!material||material.topicId!==State.topicId)throw Error('Invalid source');const page=pageText?Number(pageText):null;if(page!==null&&(!Number.isInteger(page)||page<1))throw Error('Enter a valid actual page');item.source={materialId,...(page?{page}:{}),label:material.name+(page?' · page '+page:'')}}await Storage.put(store,item);const row=await Storage.get('meta','topicConcepts:'+State.topicId),concept=row.value.concepts.find(c=>c.id===conceptId);if(item.source&&concept&&!concept.source){concept.source=item.source;await Storage.put('meta',row)}toast('Concept and source linked without changing item content.')}

async function saveConcepts(){const id=State.topicId,row=await Storage.get('meta','topicConcepts:'+id),old=row?.value?.concepts||[],names=document.getElementById('topicConceptLines').value.split('\n').map(s=>s.trim()).filter(Boolean);const added=names.filter(title=>!old.some(c=>c.title===title)).map(title=>({id:uid('concept'),title,topicId:id,type:'fact',importance:'normal',source:null}));await Storage.put('meta',{id:'topicConcepts:'+id,value:{schemaVersion:1,concepts:[...old,...added]},updatedAt:now()});closeSheet();toast('Concepts saved. Existing concepts preserved.')}
})();
