const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const root=path.resolve(__dirname,'..'),context={};vm.createContext(context);vm.runInContext(fs.readFileSync(root+'/js/study-core.js','utf8'),context);const C=context.UniversalStudyCore,t=Date.parse('2026-10-03T00:00:00Z');
let r=C.apply({}, {correct:true,confidence:'Confident'}, {now:t,mode:'strict',appearance:'one'});assert.equal(r.verified,1);assert(!r.mastered);
r=C.apply(r,{correct:true,confidence:'Confident'},{now:t+1000,mode:'strict',appearance:'two'});assert.equal(r.verified,1,'immediate repeats cannot supply strict evidence');
r=C.apply(r,{correct:true,confidence:'Confident'},{now:t+11*60000,mode:'strict',appearance:'three'});assert(r.mastered);
r=C.apply(r,{correct:false,confidence:'Confident'},{now:t+12*60000,mode:'strict',appearance:'four'});assert.equal(r.verified,0);assert(r.misconception);assert(!r.mastered);
const p=C.priority(r);assert(p>C.priority({incorrect:1,reviewAgain:true}));r=C.apply(r,{correct:true,assisted:true},{now:t+20*60000,mode:'strict'});assert.equal(r.verified,0);assert.equal(r.assistedCorrect,1);
for(const confidence of ['Guess','Unsure']){const guess=C.apply({}, {correct:true,confidence}, {now:t,mode:'mastery'});assert.equal(guess.verified,0);assert(!guess.mastered)}
let m={};for(let i=0;i<3;i++)m=C.apply(m,{correct:true},{now:t+i*C.DAY,mode:'mastery',appearance:'m'+i});assert(m.mastered);assert.equal(m.verified,3);
let rapid={};for(let i=0;i<3;i++)rapid=C.apply(rapid,{correct:true},{now:t+i*60000,mode:'mastery',appearance:'r'+i});assert(!rapid.mastered);assert.equal(rapid.verified,1);
const self=C.apply({}, {correct:true,source:'self',answer:'Good'}, {now:t,mode:'strict'});assert.equal(self.verified,0);assert.equal(self.events.length,1);
const cram=C.apply({}, {correct:false,confidence:'Confident'}, {now:t,reviewType:'cram'}),long=C.apply({}, {correct:false}, {now:t,reviewType:'long-term'});assert(new Date(cram.dueAt)<new Date(long.dueAt));
const historical={unknownField:'preserve',events:[{id:'old',rating:'Hard'}]};const upgraded=C.apply(historical,{correct:true},{now:t});assert.equal(upgraded.unknownField,'preserve');assert.equal(upgraded.events[0].id,'old');assert.equal(historical.events.length,1);
const items=Array.from({length:1000},(_,i)=>({key:'q'+i,kind:'mcq',conceptId:'c'+i,topicId:'topic'+i%10,prompt:'Q'+i,options:['a','b'],correct:i%2}));const concepts=Array.from({length:1100},(_,i)=>({id:'c'+i,title:'Concept '+i}));const started=performance.now();const test=C.blueprint(items,100);assert.equal(new Set(test.map(q=>q.key)).size,100);assert.equal(new Set(test.map(q=>q.topicId)).size,10);const coverage=C.coverage(concepts,items,{'q0':{attempts:3,correct:2,incorrect:1}});assert.equal(coverage.filter(c=>c.tested).length,1);assert.equal(coverage.filter(c=>!c.items.length).length,100);assert(!coverage[0].mastered);assert(performance.now()-started<2000);
assert(!C.validateQuestion({prompt:'bad',options:['a'],correct:7}));assert(C.validateQuestion(items[0]));console.log('PASS: Strict/Mastery spacing, assisted/guess/self exclusion, misconception priority, long-term/cram differences, complete history, 1,100-concept coverage and 1,000-question fixed blueprint.');
