const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path'),root=path.resolve(__dirname,'..'),code=fs.readFileSync(root+'/js/app.js','utf8');const engine=fs.readFileSync(root+'/js/shared-study.js','utf8'),adapter=JSON.parse(code.match(/const SHARED_STUDY_ADAPTER=([^\n]+);/)[1]);const bundles=vm.runInNewContext(code.slice(code.indexOf('const BUNDLED_MODULES='),code.indexOf('const STORES='))+';BUNDLED_MODULES');
const STORE=new Map();
function DB(){return{objectStoreNames:{contains:()=>true},transaction(){const tx={};tx.objectStore=()=>({get(id){const r={};queueMicrotask(()=>{r.result=STORE.has(id)?{id,value:structuredClone(STORE.get(id))}:undefined;r.onsuccess?.()});return r},put(row){STORE.set(row.id,structuredClone(row.value))}});queueMicrotask(()=>tx.oncomplete?.());return tx}}}
function fakeEl(){return {textContent:'',innerHTML:'',isConnected:false,firstElementChild:null,querySelector:()=>null,querySelectorAll:()=>[],appendChild(){},setAttribute(){},classList:{add(){},toggle(){}},focus(){},remove(){}}}
async function boot(id,legacy){
 const elements=new Map();const ctx={console,structuredClone,Map,Set,Date,Math,JSON,Number,String,Object,Array,Promise,RegExp,setTimeout,clearTimeout,setInterval,clearInterval,queueMicrotask,crypto:require('crypto').webcrypto,window:null,document:{getElementById:id=>{if(!elements.has(id))elements.set(id,fakeEl());return elements.get(id)},querySelectorAll:()=>[],body:{appendChild(){},addEventListener(){}},createElement:()=>fakeEl(),documentElement:{dataset:{}}},indexedDB:{open(){const r={};queueMicrotask(()=>{r.result=DB();r.onsuccess()});return r}},addEventListener(){},localStorage:{getItem:()=>null,setItem(){}},navigator:{},};ctx.window=ctx;ctx.parent=ctx;ctx.window.scrollTo=()=>{};vm.createContext(ctx);
 const html=Buffer.from(bundles.find(b=>b.moduleId===id).bundledBase64,'base64').toString();let original=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes(id==='hospital-pharmacy-midterms'?'const QUESTIONS=':'const DATA='));assert(original,'original academic data script');if(id==='hospital-pharmacy-midterms'){original=original.slice(0,original.indexOf('let state=loadState();'))+'let state='+JSON.stringify(legacy||{quizHistory:{},mastery:{},mistakes:{},flashcardState:{mastered:{},reviewAgain:{}},notes:{general:'',hits:'',topics:{}},annotations:{}})+';function normalizeState(x){return x}';}else{original=original.slice(0,original.indexOf("const STORE="))+"const STORE='ch25_diabetes_study_v2';let state="+JSON.stringify(legacy||{quizAnswers:{},annotations:{},hits:[]})+';function ensureState(){}';}
 vm.runInContext(original,ctx);vm.runInContext(adapter,ctx);vm.runInContext(fs.readFileSync(root+'/js/study-core.js','utf8'),ctx);
 // Use unchanged production logic; suppress only DOM rendering in this unit harness.
 let tested=engine.replace(/function render\(\)\{[\s\S]*?\n\}\nfunction heading/, 'function render(){}\nfunction heading');tested=tested.replace(/mount\(\);if\(!\[[\s\S]*?await flush\(\);/, 'window.__bootDone=true;');vm.runInContext(tested,ctx);
 for(let i=0;i<100&&!ctx.__bootDone;i++)await new Promise(r=>setTimeout(r,2));assert(ctx.__bootDone,'engine initialized');return ctx.StudyApp;
}
(async()=>{
STORE.set('sharedStudy:hospital-pharmacy-midterms',{schemaVersion:1,moduleId:'hospital-pharmacy-midterms',settings:{},records:{'mcq:1':{attempts:9,correct:7,incorrect:2,mastered:true,events:[{id:'legacy-kept'}],unknownField:'keep'}},sessions:{},mistakes:[{id:'old-mistake',key:'mcq:1',resolved:false}],history:[],mode:'strict',notes:{keep:'note'},bookmarks:{keep:true},migration:{}});
const h=await boot('hospital-pharmacy-midterms',{notes:{general:'Keep notes',hits:'',topics:{}},quizHistory:{},mastery:{},mistakes:{},annotations:{0:[{ink:true}]},flashcardState:{mastered:{},reviewAgain:{}},readerIndex:4});
const d=await boot('pharmacology-ch25-diabetes',{quizAnswers:{0:1},annotations:{0:[{ink:'diabetes'}]},hits:[{note:'private'}],readerPage:6,textHighlights:{0:['keep']}});
assert.equal(h.model.questions.length,200);assert.equal(d.model.questions.length,180);assert.equal(h.data.schemaVersion,2);assert(STORE.has('sharedStudyUpgradeBackup:hospital-pharmacy-midterms:v1'));assert.equal(h.record('mcq:1').attempts,9);assert.equal(h.record('mcq:1').events[0].id,'legacy-kept');assert.equal(h.data.notes.keep,'note');assert.equal(h.adapter.getLegacy().readerIndex,4);assert.equal(d.adapter.getLegacy().readerPage,6);
const q=h.model.questions[5];h.start('mcq','all','all',20,'test');let s=h.data.sessions.mcq;s.pos=s.queue.findIndex(e=>e.key===q.key);if(s.pos<0){s.queue[0]={key:q.key,ticket:'test'};s.pos=0}s.confidence[s.queue[s.pos].ticket]='Confident';h.evidence(q,false,'automatic','wrong');assert(h.record(q.key).misconception);assert.equal(h.data.mistakes.at(-1).confidence,'Confident');assert.equal(h.data.mistakes.at(-1).status,'ACTIVE');
s.confidence[s.queue[s.pos].ticket]='Confident';h.evidence(q,true,'automatic','right');assert.equal(h.data.mistakes.at(-1).status,'IMPROVING');assert(!h.data.mistakes.at(-1).resolved);const verified=h.record(q.key).verified;h.evidence(q,true);assert.equal(h.record(q.key).verified,verified,'same appearance cannot count twice');h.mark(q,true,true);assert.equal(h.data.mistakes.at(-1).status,'IMPROVING','manual mastery does not erase misconception evidence');assert(!d.record(q.key).mastered);
h.start('exam','all','all',50,'fixed',{feedback:'after'});const exam=h.data.sessions.exam,order=exam.queue.map(e=>e.key);h.evidence(h.model.questions[20],false);assert.deepEqual(exam.queue.map(e=>e.key),order,'exam question set is fixed');assert(!exam.adaptive);assert.equal(new Set(exam.queue.map(e=>e.key)).size,50);
const count=h.stats().conceptsSeen;h.navigate('reader');assert.equal(h.stats().conceptsSeen,count,'reading is not retrieval coverage');await h.flush();await d.flush();const again=await boot('hospital-pharmacy-midterms');assert.equal(again.record(q.key).attempts,h.record(q.key).attempts);assert.equal(again.adapter.getLegacy().notes.general,'Keep notes');assert.equal(d.adapter.getLegacy().textHighlights[0][0],'keep');console.log('PASS: both original banks, v1 recovery migration, preserved notes/ink/reader records, misconception/mistake lifecycle, same-appearance exclusion, isolated mastery, fixed exams and transactional reopening.');
})().catch(e=>{console.error(e);process.exitCode=1});
