"""Finalize the static app and stage only public application assets for GitHub Pages."""
from pathlib import Path
import hashlib,json,re,shutil,argparse
ROOT=Path(__file__).resolve().parents[1]
def finalize(output=None):
    vpath=ROOT/'js/version.js'
    version=re.search(r'APP_VERSION\s*=\s*["\']([^"\']+)',vpath.read_text()).group(1)
    files=[ROOT/'index.html',ROOT/'manifest.webmanifest',ROOT/'offline.html']
    for directory in ['css','js','assets']:
        files.extend(p for p in (ROOT/directory).rglob('*') if p.is_file() and p!=vpath)
    files.sort(key=lambda p:p.relative_to(ROOT).as_posix())
    digest=hashlib.sha256(version.encode())
    # Include the SW implementation in its identity; its generated first line is excluded.
    worker=ROOT/'service-worker.js';body=worker.read_text().split('\n',1)[1]
    digest.update(body.encode())
    for p in files:digest.update(p.relative_to(ROOT).as_posix().encode());digest.update(p.read_bytes())
    revision=digest.hexdigest()[:20]
    vpath.write_text('// Central application version. Revision is generated by tools/build.py.\nself.APP_VERSION = '+json.dumps(version)+';\nself.STUDY_APP_BUILD = Object.freeze({version:self.APP_VERSION,revision:'+json.dumps(revision)+'});\n')
    files.append(vpath)
    assets=[{'path':p.relative_to(ROOT).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]
    (ROOT/'precache-manifest.js').write_text('// Generated allow-list of public app assets, never user library data.\nself.STUDY_APP_ASSETS = '+json.dumps(assets,separators=(',',':'))+';\n')
    worker.write_text('// build: '+revision+'\n'+body)
    if output:
        target=Path(output).resolve()
        if target==ROOT or ROOT in target.parents and target.name!='_site':raise ValueError('Use a separate staging directory or _site.')
        if target.exists() and any(target.iterdir()):raise ValueError('Staging directory must be empty; use a new folder to avoid publishing unrelated files.')
        target.mkdir(parents=True,exist_ok=True)
        for p in [*files,worker,ROOT/'precache-manifest.js',ROOT/'.nojekyll']:
            dest=target/p.relative_to(ROOT);dest.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dest)
    print(f'PWA {version} · build {revision} · {len(assets)} offline app assets')
    return revision
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--output');args=parser.parse_args();finalize(args.output)
